version: "3"

services:
  database:
    image: postgres
    container_name: pg-rentx
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentx
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    depends_on:
      - database
    volumes:
      - .:/usr/app
    networks:
      - rentx

volumes:
  pgdata:
    driver: local

networks:
  rentx:
    driver: bridge
