version: "3"

services:
  database:
    image: postgres
    container_name: pg-rentalx
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentalx
      - POSTGRES_PASSWORD=rentalx
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentalx
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - rentalx

volumes:
  pgdata:
    driver: local

networks:
  rentalx:
    driver: bridge
